version: '3.9'

services:
  ag-restana:
    image: gateway
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ag-restana
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
